# Generated by Django 5.2.1 on 2025-06-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingjob',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trainingjob',
            name='progress',
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='metrics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
